DROP TABLE IF EXISTS flyway_schema_history CASCADE;
DROP TABLE IF EXISTS payment_requests CASCADE;
DROP TABLE IF EXISTS milestones CASCADE;
DROP TABLE IF EXISTS jobs CASCADE;
DROP TABLE IF EXISTS users CASCADE;
CREATE SCHEMA IF NOT EXISTS public;