DROP TABLE IF EXISTS flyway_schema_history cascade;
DROP TABLE IF EXISTS payment_requests cascade;
DROP TABLE IF EXISTS disputes cascade;
DROP TABLE IF EXISTS stripe_accounts cascade;
DROP TABLE IF EXISTS stripe_customers cascade;
DROP TABLE IF EXISTS milestones cascade;
DROP TABLE IF EXISTS milestone_submissions cascade;
DROP TABLE IF EXISTS milestone_submission_file cascade;
DROP TABLE IF EXISTS jobs cascade ;
DROP TABLE IF EXISTS users cascade;
DROP TABLE IF EXISTS stripe_webhook_logs cascade;
DROP TABLE IF EXISTS bank_payment_sessions cascade;
DROP TYPE IF EXISTS email_status cascade;
DROP TYPE IF EXISTS email_template_type cascade;
DROP TABLE IF EXISTS email_logs cascade;
DROP TABLE IF EXISTS bank_payment_audit_log cascade;
