package com.trustbridge.Domain.Enums;

public enum EmailTemplateType {
    WELCOME_FREELANCER,
    WELCOME_CLIENT,
    PASSWORD_RESET,

    JOB_INVITATION,
    MILESTONE_FUNDING_REQUEST,
    MILESTONE_FUNDED_FREELANCER_NOTICE,
    WORK_SUBMITTED_FOR_REVIEW,

    PAYMENT_RECEIPT,
    PAYMENT_PROCESSED,
    REFUND_PROCESSED,

    DISPUTE_OPENED,
    DISPUTE_EVIDENCE_OPENED,
    DISPUTE_RESOLVED
}
